# 04_I2C_HTS221/Makefile
# --- Project Specific Configuration ---

# 1. Define the source files for THIS project
# Note: startup.c is handled automatically by base.mk
SRCS = src/main.c

# 2. Define the project name (optional, if you want custom binary names)
PROJECT_NAME = main

# --- Include the Shared SDK Logic ---
# This pulls in the compiler flags, common sources, and build rules
include ../shared/base.mk